// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/svett/giraffe"
)

type FakeLogger struct {
	PrintlnStub        func(...interface{})
	printlnMutex       sync.RWMutex
	printlnArgsForCall []struct {
		arg1 []interface{}
	}
}

func (fake *FakeLogger) Println(arg1 ...interface{}) {
	fake.printlnMutex.Lock()
	fake.printlnArgsForCall = append(fake.printlnArgsForCall, struct {
		arg1 []interface{}
	}{arg1})
	fake.printlnMutex.Unlock()
	if fake.PrintlnStub != nil {
		fake.PrintlnStub(arg1...)
	}
}

func (fake *FakeLogger) PrintlnCallCount() int {
	fake.printlnMutex.RLock()
	defer fake.printlnMutex.RUnlock()
	return len(fake.printlnArgsForCall)
}

func (fake *FakeLogger) PrintlnArgsForCall(i int) []interface{} {
	fake.printlnMutex.RLock()
	defer fake.printlnMutex.RUnlock()
	return fake.printlnArgsForCall[i].arg1
}

var _ giraffe.Logger = new(FakeLogger)
