// This file was generated by counterfeiter
package fakes

import (
	"html/template"
	"sync"

	"github.com/svett/giraffe"
)

type FakeHTMLTemplateProvider struct {
	ProvideStub        func() (*template.Template, error)
	provideMutex       sync.RWMutex
	provideArgsForCall []struct{}
	provideReturns struct {
		result1 *template.Template
		result2 error
	}
}

func (fake *FakeHTMLTemplateProvider) Provide() (*template.Template, error) {
	fake.provideMutex.Lock()
	fake.provideArgsForCall = append(fake.provideArgsForCall, struct{}{})
	fake.provideMutex.Unlock()
	if fake.ProvideStub != nil {
		return fake.ProvideStub()
	} else {
		return fake.provideReturns.result1, fake.provideReturns.result2
	}
}

func (fake *FakeHTMLTemplateProvider) ProvideCallCount() int {
	fake.provideMutex.RLock()
	defer fake.provideMutex.RUnlock()
	return len(fake.provideArgsForCall)
}

func (fake *FakeHTMLTemplateProvider) ProvideReturns(result1 *template.Template, result2 error) {
	fake.ProvideStub = nil
	fake.provideReturns = struct {
		result1 *template.Template
		result2 error
	}{result1, result2}
}

var _ giraffe.HTMLTemplateProvider = new(FakeHTMLTemplateProvider)
